<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_John</name>
   <tag></tag>
   <elementGuidId>f1d94478-6ddf-4588-90cf-a82d24e14514</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div[2]/div[3]/div/div/div[5]/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/div[3]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>62cc1fc4-698b-4eb5-ab7a-10d84fd13391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InovuaReactDataGrid__cell__content</value>
      <webElementGuid>2047ad1f-2c7d-4556-9be6-226994d68b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>John</value>
      <webElementGuid>8f7089f4-24eb-4130-ab81-c0f1d8f2c154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;src_app__5iKs1 flex flex-column db-l&quot;]/div[@class=&quot;Body_body__p3UjE w-100 mw9 center flex flex-row flex-nowrap undefined&quot;]/div[@class=&quot;Body_container__v6RKk flex-auto&quot;]/div[@class=&quot;global-docs-page mt3 DocsPage_docsPage__OHSpF&quot;]/div[@class=&quot;DocsPage_section__6emcd&quot;]/div[@class=&quot;section-body DocsPage_sectionBody__bJlHx&quot;]/div[@class=&quot;global-snippet Snippet_snippet__VJv3a&quot;]/div[@class=&quot;PreviewResult_preview__bKw4P global-preview-result&quot;]/div[1]/div[@class=&quot;InovuaReactDataGrid InovuaReactDataGrid--theme-default-dark InovuaReactDataGrid--columns-ready InovuaReactDataGrid--zebra-rows InovuaReactDataGrid--show-hover-rows InovuaReactDataGrid--direction-ltr InovuaReactDataGrid--no-header-border-right InovuaReactDataGrid--cell-borders-horizontal InovuaReactDataGrid--cell-borders-vertical&quot;]/div[@class=&quot;InovuaReactDataGrid__body&quot;]/div[@class=&quot;InovuaReactDataGrid__column-layout&quot;]/div[@class=&quot;InovuaReactDataGrid__virtual-list inovua-react-virtual-list inovua-react-virtual-list--theme-default-dark inovua-react-virtual-list--virtual-scroll inovua-react-scroll-container--block inovua-react-scroll-container inovua-react-scroll-container--theme-default-dark&quot;]/div[@class=&quot;inovua-react-scroll-container__wrapper&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;inovua-react-virtual-list__view-container&quot;]/div[@class=&quot;inovua-react-virtual-list__row-container&quot;]/div[@class=&quot;InovuaReactDataGrid__row InovuaReactDataGrid__row--direction-ltr InovuaReactDataGrid__row--odd InovuaReactDataGrid__row--no-locked-start InovuaReactDataGrid__row--no-locked-end InovuaReactDataGrid__row--show-horizontal-borders InovuaReactDataGrid__row--rowheight&quot;]/div[@class=&quot;InovuaReactDataGrid__row-cell-wrap InovuaReactDataGrid__row-hover-target&quot;]/div[@class=&quot;InovuaReactDataGrid__cell InovuaReactDataGrid__cell--unlocked InovuaReactDataGrid__cell--direction-ltr InovuaReactDataGrid__cell--user-select-none InovuaReactDataGrid__cell--first InovuaReactDataGrid__cell--first-in-section InovuaReactDataGrid__cell--show-border-bottom InovuaReactDataGrid__cell--active-row-left-border&quot;]/div[@class=&quot;InovuaReactDataGrid__cell__content&quot;]</value>
      <webElementGuid>c8daa795-7eeb-48d0-99a1-fa2c649bcacb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/div[3]/div/div/div[5]/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/div[3]/div/div/div</value>
      <webElementGuid>9f54d8cc-8ea8-44f7-85a1-3bf2a7baff2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New York'])[1]/following::div[6]</value>
      <webElementGuid>6e30e97a-5df1-444f-bedf-55bd4dc55f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mary'])[1]/following::div[11]</value>
      <webElementGuid>9efe7936-cb86-4753-8483-8e57273f3f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='London'])[1]/preceding::div[4]</value>
      <webElementGuid>22306f6a-465a-40b9-acd5-4c89e1b7334e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boby'])[1]/preceding::div[8]</value>
      <webElementGuid>c076bcf5-34ca-4efc-97fb-d16a7bf593e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='John']/parent::*</value>
      <webElementGuid>7edde1f4-a142-40ad-9bcf-c9bfd83b62e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[3]/div/div/div</value>
      <webElementGuid>c483c39c-e1ee-4fb9-92ba-e7e0597ebfee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'John' or . = 'John')]</value>
      <webElementGuid>b4c84975-e29e-4f6a-b761-0433c38fda19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
