<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prabal_inovua-react-toolkit-text-input__input</name>
   <tag></tag>
   <elementGuidId>b8bd4b25-2647-4d70-a0b3-82e655f61756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.inovua-react-toolkit-text-input__input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Prabal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7cbefeba-db17-45e9-b630-8780b33ca29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cd1e7458-eb29-40a6-8e86-3892c74d443a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inovua-react-toolkit-text-input__input</value>
      <webElementGuid>786cf0d1-4baa-44d9-bdfc-8f2c37ee823b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>852ef4d6-5ca4-4fe0-a5da-5f58b114006d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Prabal</value>
      <webElementGuid>63b98ea4-49a1-46e3-8c64-9315c156e3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;src_app__5iKs1 flex flex-column db-l&quot;]/div[@class=&quot;Body_body__p3UjE w-100 mw9 center flex flex-row flex-nowrap undefined&quot;]/div[@class=&quot;Body_container__v6RKk flex-auto&quot;]/div[@class=&quot;global-docs-page mt3 DocsPage_docsPage__OHSpF&quot;]/div[@class=&quot;DocsPage_section__6emcd&quot;]/div[@class=&quot;section-body DocsPage_sectionBody__bJlHx&quot;]/div[@class=&quot;global-snippet Snippet_snippet__VJv3a&quot;]/div[@class=&quot;PreviewResult_preview__bKw4P global-preview-result&quot;]/div[1]/div[@class=&quot;InovuaReactDataGrid InovuaReactDataGrid--theme-default-dark InovuaReactDataGrid--columns-ready InovuaReactDataGrid--zebra-rows InovuaReactDataGrid--focused InovuaReactDataGrid--show-hover-rows InovuaReactDataGrid--direction-ltr InovuaReactDataGrid--no-header-border-right InovuaReactDataGrid--cell-borders-horizontal InovuaReactDataGrid--cell-borders-vertical&quot;]/div[@class=&quot;InovuaReactDataGrid__body&quot;]/div[@class=&quot;InovuaReactDataGrid__column-layout&quot;]/div[@class=&quot;InovuaReactDataGrid__virtual-list inovua-react-virtual-list inovua-react-virtual-list--theme-default-dark inovua-react-virtual-list--virtual-scroll inovua-react-scroll-container--block inovua-react-scroll-container inovua-react-scroll-container--theme-default-dark&quot;]/div[@class=&quot;inovua-react-scroll-container__wrapper&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;inovua-react-virtual-list__view-container&quot;]/div[@class=&quot;inovua-react-virtual-list__row-container&quot;]/div[@class=&quot;InovuaReactDataGrid__row InovuaReactDataGrid__row--editing InovuaReactDataGrid__row--direction-ltr InovuaReactDataGrid__row--odd InovuaReactDataGrid__row--no-locked-start InovuaReactDataGrid__row--no-locked-end InovuaReactDataGrid__row--show-horizontal-borders InovuaReactDataGrid__row--active InovuaReactDataGrid__row--rowheight InovuaReactDataGrid__row--focused&quot;]/div[@class=&quot;InovuaReactDataGrid__row-cell-wrap InovuaReactDataGrid__row-hover-target&quot;]/div[@class=&quot;InovuaReactDataGrid__cell InovuaReactDataGrid__cell--unlocked InovuaReactDataGrid__cell--direction-ltr InovuaReactDataGrid__cell--user-select-none InovuaReactDataGrid__cell--in-edit InovuaReactDataGrid__cell--first InovuaReactDataGrid__cell--first-in-section InovuaReactDataGrid__cell--show-border-bottom InovuaReactDataGrid__cell--active-row-left-border&quot;]/div[@class=&quot;inovua-react-toolkit-text-input InovuaReactDataGrid__cell__editor InovuaReactDataGrid__cell__editor--text  inovua-react-toolkit-text-input--ltr inovua-react-toolkit-text-input--theme-default-dark inovua-react-toolkit-text-input--enable-clear-button inovua-react-toolkit-text-input--focused&quot;]/input[@class=&quot;inovua-react-toolkit-text-input__input&quot;]</value>
      <webElementGuid>89be0793-eb96-4c1f-b3bf-19a2d8f338c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Prabal']</value>
      <webElementGuid>60de10b9-08f1-4026-a6fc-ae2116699dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/div[3]/div/div/div[5]/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/div[3]/div/div/div[2]/input</value>
      <webElementGuid>6cebe38f-5b01-4189-b850-8b57d04abd2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6ddd3de0-4587-4ae9-81f9-24d01ac4f2d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>4c47275f-1a94-42a6-a14d-91ed4a7587d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
