<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_inovua-react-toolkit-text-input__input</name>
   <tag></tag>
   <elementGuidId>48683d50-f15b-4941-9f9c-9bcded1f38cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.inovua-react-toolkit-text-input__input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='John']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfd7e095-c469-471b-bf27-2c1772e6b2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c703f5e1-b755-4b62-9407-3877f0786891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inovua-react-toolkit-text-input__input</value>
      <webElementGuid>2bfad1a8-5d88-47d5-8b38-7f034b4ed040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08c75739-a9b7-4bb4-ac6e-b38091c4b190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>John</value>
      <webElementGuid>6d5aa12b-a3b7-42bd-b8f8-b9a65557b069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;src_app__5iKs1 flex flex-column db-l&quot;]/div[@class=&quot;Body_body__p3UjE w-100 mw9 center flex flex-row flex-nowrap undefined&quot;]/div[@class=&quot;Body_container__v6RKk flex-auto&quot;]/div[@class=&quot;global-docs-page mt3 DocsPage_docsPage__OHSpF&quot;]/div[@class=&quot;DocsPage_section__6emcd&quot;]/div[@class=&quot;section-body DocsPage_sectionBody__bJlHx&quot;]/div[@class=&quot;global-snippet Snippet_snippet__VJv3a&quot;]/div[@class=&quot;PreviewResult_preview__bKw4P global-preview-result&quot;]/div[1]/div[@class=&quot;InovuaReactDataGrid InovuaReactDataGrid--theme-default-dark InovuaReactDataGrid--columns-ready InovuaReactDataGrid--zebra-rows InovuaReactDataGrid--focused InovuaReactDataGrid--show-hover-rows InovuaReactDataGrid--direction-ltr InovuaReactDataGrid--no-header-border-right InovuaReactDataGrid--cell-borders-horizontal InovuaReactDataGrid--cell-borders-vertical&quot;]/div[@class=&quot;InovuaReactDataGrid__body&quot;]/div[@class=&quot;InovuaReactDataGrid__column-layout&quot;]/div[@class=&quot;InovuaReactDataGrid__virtual-list inovua-react-virtual-list inovua-react-virtual-list--theme-default-dark inovua-react-virtual-list--virtual-scroll inovua-react-scroll-container--block inovua-react-scroll-container inovua-react-scroll-container--theme-default-dark&quot;]/div[@class=&quot;inovua-react-scroll-container__wrapper&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;inovua-react-virtual-list__view-container&quot;]/div[@class=&quot;inovua-react-virtual-list__row-container&quot;]/div[@class=&quot;InovuaReactDataGrid__row InovuaReactDataGrid__row--editing InovuaReactDataGrid__row--direction-ltr InovuaReactDataGrid__row--odd InovuaReactDataGrid__row--no-locked-start InovuaReactDataGrid__row--no-locked-end InovuaReactDataGrid__row--show-horizontal-borders InovuaReactDataGrid__row--active InovuaReactDataGrid__row--rowheight InovuaReactDataGrid__row--focused&quot;]/div[@class=&quot;InovuaReactDataGrid__row-cell-wrap InovuaReactDataGrid__row-hover-target&quot;]/div[@class=&quot;InovuaReactDataGrid__cell InovuaReactDataGrid__cell--unlocked InovuaReactDataGrid__cell--direction-ltr InovuaReactDataGrid__cell--user-select-none InovuaReactDataGrid__cell--in-edit InovuaReactDataGrid__cell--first InovuaReactDataGrid__cell--first-in-section InovuaReactDataGrid__cell--show-border-bottom InovuaReactDataGrid__cell--active-row-left-border&quot;]/div[@class=&quot;inovua-react-toolkit-text-input InovuaReactDataGrid__cell__editor InovuaReactDataGrid__cell__editor--text  inovua-react-toolkit-text-input--ltr inovua-react-toolkit-text-input--theme-default-dark inovua-react-toolkit-text-input--enable-clear-button inovua-react-toolkit-text-input--focused&quot;]/input[@class=&quot;inovua-react-toolkit-text-input__input&quot;]</value>
      <webElementGuid>00695e1f-a3a4-44ba-ab11-90aefa82e553</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='John']</value>
      <webElementGuid>c24d2ca5-4dc1-40c5-9308-39a9a979a28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/div[3]/div/div/div[5]/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div/div[3]/div/div/div[2]/input</value>
      <webElementGuid>00fcc0ea-ac37-4747-bd50-f1678feccfd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>8a5c2b76-7b57-444d-9d86-933b837f5484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>d8558177-faba-4488-9c74-15617a6b11a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
