<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_21</name>
   <tag></tag>
   <elementGuidId>4aa149b4-5810-44c7-9f67-a14ea7b108d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[3]/div/div[5]/div/div/div/div/div/div[2]/div/div[5]/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>228b61fa-73a4-41a0-8532-8773fb4f9bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inovua-react-toolkit-calendar__month-view-day-text</value>
      <webElementGuid>d489fd8d-d377-4967-a706-4db4720f6eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>72d8e9a3-d1c5-42c1-9284-4233bc57aa67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;datagrid-demo__app datagrid-demo__app--theme-default-dark&quot;]/div[@class=&quot;datagrid-demo__app-content&quot;]/div[@class=&quot;InovuaReactDataGrid datagrid-demo__grid datagrid-demo__grid__font-family--nunito InovuaReactDataGrid--theme-default-dark InovuaReactDataGrid--columns-ready InovuaReactDataGrid--zebra-rows InovuaReactDataGrid--filterable InovuaReactDataGrid--focused InovuaReactDataGrid--show-hover-rows InovuaReactDataGrid--direction-ltr InovuaReactDataGrid--show-header-border-right InovuaReactDataGrid--show-border-right InovuaReactDataGrid--cell-borders-horizontal InovuaReactDataGrid--cell-borders-vertical&quot;]/div[@class=&quot;InovuaReactDataGrid__portal-host&quot;]/div[@class=&quot;inovua-react-toolkit-date-input__overlay inovua-react-toolkit-date-input__overlay--visible inovua-react-toolkit-date-input__overlay--position-fixed&quot;]/div[@class=&quot;inovua-react-toolkit-date-input__overlay__content&quot;]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-toolkit-date-input__picker inovua-react-toolkit-calendar__calendar inovua-react-toolkit-calendar__calendar--theme-default-dark inovua-react-toolkit-flex-v3--align-items-center inovua-react-toolkit-flex-v3--row inovua-react-toolkit-flex-v3--display-inline-flex&quot;]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-toolkit-calendar__month-view inovua-react-toolkit-calendar__month-view--theme-default-dark inovua-react-toolkit-calendar__month-view-relative inovua-react-toolkit-calendar__month-view inovua-react-toolkit-flex-v3--align-items-stretch inovua-react-toolkit-flex-v3--column inovua-react-toolkit-flex-v3--display-inline-flex&quot;]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-toolkit-flex-v3--align-items-stretch inovua-react-toolkit-flex-v3--column inovua-react-toolkit-flex-v3--display-flex&quot;]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-toolkit-flex-v3--align-items-center inovua-react-toolkit-flex-v3--justify-content-center inovua-react-toolkit-flex-v3--row inovua-react-toolkit-flex-v3--display-flex&quot;]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-toolkit-flex-v3--align-items-stretch inovua-react-toolkit-flex-v3--column inovua-react-toolkit-flex-v3--flex-grow-1 inovua-react-toolkit-flex-v3--flex-shrink-0 inovua-react-toolkit-flex-v3--flex-basis-auto inovua-react-toolkit-flex-v3--display-flex&quot;]/div[@class=&quot;inovua-react-toolkit-calendar__month-view-row&quot;]/div[@class=&quot;inovua-react-toolkit-calendar__month-view-day--this-month inovua-react-toolkit-calendar__month-view-cell inovua-react-toolkit-calendar__month-view-day&quot;]/div[@class=&quot;inovua-react-toolkit-calendar__month-view-day-text&quot;]</value>
      <webElementGuid>216177a5-b040-4a89-9c74-89c40f8e40a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[3]/div/div[5]/div/div/div/div/div/div[2]/div/div[5]/div[4]/div</value>
      <webElementGuid>9b955607-41bf-4446-b38d-eecd969b92bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::div[56]</value>
      <webElementGuid>6e4282e8-ac0b-4712-89e2-ea2b3842fb08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::div[57]</value>
      <webElementGuid>3d526a41-0772-4c2d-a03e-6d2e0daa5406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::div[41]</value>
      <webElementGuid>dfbc92eb-01bc-4eec-8379-1899a6c50e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Theme settings'])[1]/preceding::div[46]</value>
      <webElementGuid>867ae744-8432-4581-b841-911ac117ffda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='21']/parent::*</value>
      <webElementGuid>433eb70f-d02d-4236-862e-2c31e269b88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/div</value>
      <webElementGuid>8830b845-b215-4f27-bade-f2d1d0373b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '21' or . = '21')]</value>
      <webElementGuid>c4e44276-28b4-495a-b23c-99a10a85cb6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
