<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dec_inovua-react-toolkit-calendar__deca_d599d0</name>
   <tag></tag>
   <elementGuidId>0c02e660-d862-4cb2-962e-5139b4285163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.inovua-react-toolkit-calendar__decade-view-arrow.inovua-react-toolkit-calendar__decade-view-arrow--prev</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[3]/div/div[5]/div/div/div/div/div/div/div[6]/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>042f4133-4654-4767-a58b-781bf5c2632a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inovua-react-toolkit-calendar__decade-view-arrow inovua-react-toolkit-calendar__decade-view-arrow--prev</value>
      <webElementGuid>4db3e37c-37b4-4516-8cce-092d3c0745ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;datagrid-demo__app datagrid-demo__app--theme-default-dark&quot;]/div[@class=&quot;datagrid-demo__app-content&quot;]/div[@class=&quot;InovuaReactDataGrid datagrid-demo__grid datagrid-demo__grid__font-family--nunito InovuaReactDataGrid--theme-default-dark InovuaReactDataGrid--columns-ready InovuaReactDataGrid--zebra-rows InovuaReactDataGrid--filterable InovuaReactDataGrid--focused InovuaReactDataGrid--show-hover-rows InovuaReactDataGrid--direction-ltr InovuaReactDataGrid--show-header-border-right InovuaReactDataGrid--show-border-right InovuaReactDataGrid--cell-borders-horizontal InovuaReactDataGrid--cell-borders-vertical&quot;]/div[@class=&quot;InovuaReactDataGrid__portal-host&quot;]/div[@class=&quot;inovua-react-toolkit-date-input__overlay inovua-react-toolkit-date-input__overlay--visible inovua-react-toolkit-date-input__overlay--position-fixed&quot;]/div[@class=&quot;inovua-react-toolkit-date-input__overlay__content&quot;]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-toolkit-date-input__picker inovua-react-toolkit-calendar__calendar inovua-react-toolkit-calendar__calendar--theme-default-dark inovua-react-toolkit-flex-v3--align-items-center inovua-react-toolkit-flex-v3--row inovua-react-toolkit-flex-v3--display-inline-flex&quot;]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-toolkit-calendar__month-view inovua-react-toolkit-calendar__month-view--theme-default-dark inovua-react-toolkit-calendar__month-view-relative inovua-react-toolkit-calendar__month-view inovua-react-toolkit-flex-v3--align-items-stretch inovua-react-toolkit-flex-v3--column inovua-react-toolkit-flex-v3--display-inline-flex&quot;]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-toolkit-flex-v3--align-items-stretch inovua-react-toolkit-flex-v3--column inovua-react-toolkit-flex-v3--display-flex&quot;]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-toolkit-calendar__nav-bar inovua-react-toolkit-calendar__nav-bar--theme-default-dark inovua-react-toolkit-calendar__nav-bar--with-month-decade-view inovua-react-toolkit-flex-v3--align-items-center inovua-react-toolkit-flex-v3--wrap inovua-react-toolkit-flex-v3--row inovua-react-toolkit-flex-v3--display-inline-flex&quot;]/div[@class=&quot;inovua-react-toolkit-calendar__nav-bar-month-decade-view-modal inovua-react-toolkit-calendar__nav-bar-month-decade-view-show-animation&quot;]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-toolkit-calendar__nav-bar-month-decade-view inovua-react-toolkit-calendar__nav-bar-month-decade-view-month inovua-react-toolkit-calendar__month-decade-view inovua-react-toolkit-calendar__month-decade-view--theme-default-dark inovua-react-toolkit-flex-v3--align-items-stretch inovua-react-toolkit-flex-v3--wrap inovua-react-toolkit-flex-v3--column inovua-react-toolkit-flex-v3--display-inline-flex&quot;]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-toolkit-calendar__decade-view inovua-react-toolkit-calendar__decade-view--theme-default-dark inovua-react-toolkit-flex-v3--align-items-center inovua-react-toolkit-flex-v3--wrap inovua-react-toolkit-flex-v3--row inovua-react-toolkit-flex-v3--display-inline-flex&quot;]/div[@class=&quot;inovua-react-toolkit-calendar__decade-view-arrow inovua-react-toolkit-calendar__decade-view-arrow--prev&quot;]</value>
      <webElementGuid>f07ef7be-0f27-4283-ba6c-04b3be1a892f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[3]/div/div[5]/div/div/div/div/div/div/div[6]/div/div[3]/div</value>
      <webElementGuid>52e0de8f-42db-4410-a52f-00553573a0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dec'])[1]/following::div[3]</value>
      <webElementGuid>d912d5a9-2a05-451c-9a27-e0d02b872867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nov'])[1]/following::div[4]</value>
      <webElementGuid>127d8bdc-95eb-4b95-a87d-50e4295871c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::div[17]</value>
      <webElementGuid>3606b2fe-2683-4899-801e-b0cec01da0c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[18]</value>
      <webElementGuid>8c40fc02-2fe6-4ea4-bfe6-2a6baf8dfec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div[6]/div/div[3]/div</value>
      <webElementGuid>806d1a9b-7caa-44ed-8b39-221126677277</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
