<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Results per page_inovua-react-toolkit-c_5e47c2</name>
   <tag></tag>
   <elementGuidId>dfda2b32-7d05-4db5-85d8-a02257da4ddf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.inovua-react-toolkit-combo-box.inovua-react-pagination-toolbar__page-size-combo.inovua-react-toolkit-combo-box--ltr.inovua-react-toolkit-combo-box--shadow.inovua-react-toolkit-combo-box--theme-default-dark > div.inovua-react-toolkit-combo-box__tools > div.inovua-react-toolkit-combo-box__toggle-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[3]/div/div/div[2]/div/div/div/div/div/div[2]/div/div[7]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c913da85-b618-48d3-8f0e-ccf024eac4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inovua-react-toolkit-combo-box__toggle-icon</value>
      <webElementGuid>fc7b0f78-6cba-4383-a721-28424e6bee1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;datagrid-demo__app datagrid-demo__app--theme-default-dark&quot;]/div[@class=&quot;datagrid-demo__app-content&quot;]/div[@class=&quot;InovuaReactDataGrid datagrid-demo__grid datagrid-demo__grid__font-family--nunito InovuaReactDataGrid--theme-default-dark InovuaReactDataGrid--columns-ready InovuaReactDataGrid--zebra-rows InovuaReactDataGrid--filterable InovuaReactDataGrid--focused InovuaReactDataGrid--show-hover-rows InovuaReactDataGrid--direction-ltr InovuaReactDataGrid--show-header-border-right InovuaReactDataGrid--show-border-right InovuaReactDataGrid--cell-borders-horizontal InovuaReactDataGrid--cell-borders-vertical&quot;]/div[@class=&quot;InovuaReactDataGrid__body&quot;]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-pagination-toolbar inovua-react-pagination-toolbar--theme-default-dark inovua-react-pagination-toolbar--ltr inovua-react-toolkit-toolbar inovua-react-toolkit-toolbar--theme-default-dark inovua-react-toolkit-toolbar--change-button-styles inovua-react-toolkit-toolbar--arrowScroller inovua-react-toolkit-toolbar inovua-react-toolkit-toolbar--direction-horizontal inovua-react-toolkit-toolbar--native-scroll inovua-react-toolkit-toolbar--theme-default-dark inovua-react-toolkit-flex-v3--align-items-start inovua-react-toolkit-flex-v3--wrap inovua-react-toolkit-flex-v3--row inovua-react-toolkit-flex-v3--display-flex&quot;]/div[@class=&quot;inovua-react-toolkit-toolbar__scroll-container inovua-react-scroll-container--block inovua-react-scroll-container inovua-react-scroll-container--theme-default-dark&quot;]/div[@class=&quot;inovua-react-scroll-container__wrapper&quot;]/div[@class=&quot;inovua-react-scroll-container__scroller inovua-react-scroll-container__scroller--direction-ltr inovua-react-scroll-container__scroller--avoid-repaint&quot;]/div[@class=&quot;inovua-react-scroll-container__view&quot;]/div[1]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-toolkit-toolbar__inner-wrapper inovua-react-toolkit-toolbar__inner-wrapper--direction-row inovua-react-toolkit-flex-v3--align-items-center inovua-react-toolkit-flex-v3--row inovua-react-toolkit-flex-v3--display-flex&quot;]/div[@class=&quot;inovua-react-pagination-toolbar__region&quot;]/div[@class=&quot;inovua-react-toolkit-combo-box inovua-react-pagination-toolbar__page-size-combo inovua-react-toolkit-combo-box--ltr inovua-react-toolkit-combo-box--shadow inovua-react-toolkit-combo-box--theme-default-dark&quot;]/div[@class=&quot;inovua-react-toolkit-combo-box__tools&quot;]/div[@class=&quot;inovua-react-toolkit-combo-box__toggle-icon&quot;]</value>
      <webElementGuid>4dc2dc9f-c276-4ad1-a2c2-6fbfba6728d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[3]/div/div/div[2]/div/div/div/div/div/div[2]/div/div[7]/div[2]/div</value>
      <webElementGuid>ff046f4f-dff2-4432-a494-d73ebbad574a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results per page'])[1]/following::div[5]</value>
      <webElementGuid>17c1f329-3d62-48e5-9a34-d0e8d4fa4553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page'])[1]/following::div[15]</value>
      <webElementGuid>9232b350-070f-42a5-a2b6-5d69cf59e628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading'])[1]/preceding::div[22]</value>
      <webElementGuid>afa9e482-940a-49e8-b589-ff57438ad5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/div[2]/div/div[7]/div[2]/div</value>
      <webElementGuid>08855e87-0886-4892-8530-7c5ef01e2b80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
