<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Roboto</name>
   <tag></tag>
   <elementGuidId>1bc2d341-c4e6-493e-a4d1-386ca23da103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.inovua-react-toolkit-combo-box__list__item.inovua-react-toolkit-combo-box__list__item--ellipsis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[3]/div[2]/div/div/div/div/div/div/div/div[2]/div[3]/div/div[2]/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd61f2f5-fc0e-4997-8de3-ef697941d68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inovua-react-toolkit-combo-box__list__item inovua-react-toolkit-combo-box__list__item--ellipsis</value>
      <webElementGuid>e6b73e62-70df-43f1-82cc-538938780f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Roboto</value>
      <webElementGuid>8af71fda-e89e-4805-a559-fa8752814083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;datagrid-demo__app datagrid-demo__app--theme-amber-dark&quot;]/div[@class=&quot;datagrid-demo__app-content&quot;]/div[@class=&quot;datagrid-demo-configurator__wrapper datagrid-demo-configurator--theme-amber-dark&quot;]/div[@class=&quot;inovua-react-scroll-container--block inovua-react-scroll-container inovua-react-scroll-container--theme-amber-dark&quot;]/div[@class=&quot;inovua-react-scroll-container__wrapper&quot;]/div[@class=&quot;inovua-react-scroll-container__scroller inovua-react-scroll-container__scroller--direction-ltr inovua-react-scroll-container__scroller--avoid-repaint&quot;]/div[@class=&quot;inovua-react-scroll-container__view&quot;]/div[1]/div[1]/div[@class=&quot;datagrid-demo-section__wrapper datagrid-demo-section--theme-amber-dark&quot;]/div[@class=&quot;datagrid-demo-section__content&quot;]/div[3]/div[@class=&quot;datagrid-demo-combo__wrapper datagrid-demo-combo--theme-amber-dark&quot;]/div[@class=&quot;inovua-react-toolkit-combo-box inovua-react-toolkit-combo-box--ltr inovua-react-toolkit-combo-box--shadow inovua-react-toolkit-combo-box--theme-amber-dark inovua-react-toolkit-combo-box--focus&quot;]/div[@class=&quot;inovua-react-toolkit-combo-box__list inovua-react-toolkit-combo-box__list--theme-amber-dark inovua-react-toolkit-combo-box__list--position-bottom&quot;]/div[@class=&quot;inovua-react-toolkit-combo-box__list__virtual-list&quot;]/div[@class=&quot;inovua-react-toolkit-combo-box__list__item inovua-react-toolkit-combo-box__list__item--ellipsis&quot;]</value>
      <webElementGuid>a83e8cbc-6d4e-4739-8eb4-9ed2d5a34ce8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[3]/div[2]/div/div/div/div/div/div/div/div[2]/div[3]/div/div[2]/div[3]/div/div</value>
      <webElementGuid>d24350f8-3fad-412d-ac76-1add9b2d1e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nunito'])[1]/following::div[7]</value>
      <webElementGuid>d05de213-2768-4fd7-bc4d-b49a4d9fb309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Font type'])[1]/following::div[10]</value>
      <webElementGuid>f084f3f6-9399-4a0c-b5f6-1e4e84322766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nunito'])[2]/preceding::div[1]</value>
      <webElementGuid>d14d9db4-1594-4894-b2a3-c2d973ae2d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lato'])[1]/preceding::div[2]</value>
      <webElementGuid>4cf060d2-853e-4aed-bb46-414c9e3e03da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Roboto']/parent::*</value>
      <webElementGuid>72d3fa1f-4766-4fe5-89f8-d9a96e2150ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[3]/div/div</value>
      <webElementGuid>40d86edb-2d79-4ac8-84cd-0de149581873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Roboto' or . = 'Roboto')]</value>
      <webElementGuid>0c614e01-047d-4710-b61d-ba7ffaf0f58d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
