<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Color_datagrid-demo-radio__item_1</name>
   <tag></tag>
   <elementGuidId>e49982cd-0a50-4976-a30e-906cce807279</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[3]/div[2]/div/div/div/div/div/div/div/div[2]/div[2]/div/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>709d7e53-5a74-4971-9fc4-f38cf1407960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datagrid-demo-radio__item</value>
      <webElementGuid>a9b05160-9447-4443-8646-e72665540135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;datagrid-demo__app datagrid-demo__app--theme-green-dark&quot;]/div[@class=&quot;datagrid-demo__app-content&quot;]/div[@class=&quot;datagrid-demo-configurator__wrapper datagrid-demo-configurator--theme-green-dark&quot;]/div[@class=&quot;inovua-react-scroll-container--block inovua-react-scroll-container inovua-react-scroll-container--theme-green-dark&quot;]/div[@class=&quot;inovua-react-scroll-container__wrapper&quot;]/div[@class=&quot;inovua-react-scroll-container__scroller inovua-react-scroll-container__scroller--direction-ltr inovua-react-scroll-container__scroller--avoid-repaint&quot;]/div[@class=&quot;inovua-react-scroll-container__view&quot;]/div[1]/div[1]/div[@class=&quot;datagrid-demo-section__wrapper datagrid-demo-section--theme-green-dark&quot;]/div[@class=&quot;datagrid-demo-section__content&quot;]/div[2]/div[@class=&quot;datagrid-demo-radio__wrapper datagrid-demo-radio--theme-green-dark&quot;]/div[@class=&quot;datagrid-demo-radio__items&quot;]/div[@class=&quot;datagrid-demo-radio__item&quot;]</value>
      <webElementGuid>88c68ec1-dd95-43c2-9055-b64b3ef1edb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[3]/div[2]/div/div/div/div/div/div/div/div[2]/div[2]/div/div[2]/div[3]</value>
      <webElementGuid>10ee447f-4930-49ef-b0bc-5ab0fbd057b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]</value>
      <webElementGuid>68d40f36-65a4-4f0f-b6c2-57da483ae6c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
