<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Sort ascending</name>
   <tag></tag>
   <elementGuidId>dfab4a25-4d2a-48d0-8ac8-d5cdcdaf3122</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.inovua-react-toolkit-menu__cell.inovua-react-toolkit-menu__cell--ltr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[3]/div/div[5]/div/div/div/div/div/div/div[2]/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a0c31048-2965-4023-bccd-5d65ce52ed1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inovua-react-toolkit-menu__cell inovua-react-toolkit-menu__cell--ltr</value>
      <webElementGuid>d1640bec-8102-4817-8c44-0ca593ec8c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>adfb9a68-f07f-4a1b-8f37-6bc520000e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sort ascending</value>
      <webElementGuid>00c7d849-4e53-47d6-84d4-77dc2846d04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;datagrid-demo__app datagrid-demo__app--theme-amber-dark&quot;]/div[@class=&quot;datagrid-demo__app-content&quot;]/div[@class=&quot;InovuaReactDataGrid datagrid-demo__grid datagrid-demo__grid__font-family--roboto InovuaReactDataGrid--theme-amber-dark InovuaReactDataGrid--columns-ready InovuaReactDataGrid--zebra-rows InovuaReactDataGrid--filterable InovuaReactDataGrid--focused InovuaReactDataGrid--show-hover-rows InovuaReactDataGrid--direction-ltr InovuaReactDataGrid--show-header-border-right InovuaReactDataGrid--show-border-right InovuaReactDataGrid--cell-borders-horizontal InovuaReactDataGrid--cell-borders-vertical&quot;]/div[@class=&quot;inovua-react-toolkit-menu inovua-react-toolkit-menu--theme-amber-dark inovua-react-toolkit-menu--ltr inovua-react-toolkit-menu--depth-0 inovua-react-toolkit-menu--has-overflow inovua-react-toolkit-menu--shadow inovua-react-toolkit-menu--has-scroll&quot;]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-toolkit-menu__scroll-container inovua-react-toolkit-arrow-scroller inovua-react-toolkit-arrow-scroller--direction-vertical inovua-react-toolkit-arrow-scroller--native-scroll inovua-react-toolkit-arrow-scroller--theme-amber-dark inovua-react-toolkit-flex-v3--align-items-start inovua-react-toolkit-flex-v3--wrap inovua-react-toolkit-flex-v3--row inovua-react-toolkit-flex-v3--display-flex&quot;]/div[@class=&quot;inovua-react-toolkit-arrow-scroller__scroll-container inovua-react-scroll-container--block inovua-react-scroll-container inovua-react-scroll-container--theme-amber-dark&quot;]/div[@class=&quot;inovua-react-scroll-container__wrapper&quot;]/div[@class=&quot;inovua-react-scroll-container__scroller inovua-react-scroll-container__scroller--direction-ltr inovua-react-scroll-container__scroller--avoid-repaint&quot;]/div[@class=&quot;inovua-react-scroll-container__view&quot;]/div[1]/div[@class=&quot;inovua-react-toolkit-flex inovua-react-toolkit-arrow-scroller__inner-wrapper inovua-react-toolkit-arrow-scroller__inner-wrapper--direction-column inovua-react-toolkit-flex-v3--align-items-center inovua-react-toolkit-flex-v3--row inovua-react-toolkit-flex-v3--display-flex&quot;]/table[@class=&quot;inovua-react-toolkit-menu__table&quot;]/tbody[1]/tr[@class=&quot;inovua-react-toolkit-menu__row inovua-react-toolkit-menu__row--over&quot;]/td[@class=&quot;inovua-react-toolkit-menu__cell inovua-react-toolkit-menu__cell--ltr&quot;]</value>
      <webElementGuid>50a97f39-cc25-4611-b981-ad40648e06a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[3]/div/div[5]/div/div/div/div/div/div/div[2]/table/tbody/tr/td</value>
      <webElementGuid>1a8d5086-403f-4246-a539-6fd01e77b405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading'])[1]/following::td[1]</value>
      <webElementGuid>bf6cb046-58cb-46c9-9a0b-5a13d42125fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort descending'])[1]/preceding::td[1]</value>
      <webElementGuid>e56fb060-bafc-4d48-816b-809fd9905d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group'])[1]/preceding::td[3]</value>
      <webElementGuid>b966be45-6892-4e17-bd5c-e64f52e8f762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sort ascending']/parent::*</value>
      <webElementGuid>bbbc2a95-d459-4770-843b-029e78ab6409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>fb98ded9-082c-404d-a508-385584790f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Sort ascending' or . = 'Sort ascending')]</value>
      <webElementGuid>efac6a16-904c-4c84-9e38-850636113e84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
